### ISSUE TITLE
Index page mentions "reply to this email"

### ISSUE THREAD

**Issue by tjguk** [PyconUK/pyconuk.github.io#1]
Not sure what change to make, so raising this as an issue rather than a PR

**Comment by hawkz** [comment]
#Fail - I quickly loaded in ntoll's draft launch text... Can someone suggest wording?

**Comment by tjguk** [comment]
I could suggest some wording if I knew how people _should_ in fact get in touch! Is there a central email address? Or should contact be via Twitter?
