### ISSUE TITLE
Vagrant config with Jekyll etc.

### ISSUE THREAD

**Issue by doismellburning** [PyconUK/pyconuk.github.io#22]
https://github.com/PyconUK/pyconuk.github.io/pull/21 - "someone who can build the site" - that should be "anyone who can run `vagrant up`" rather than "anyone who can set up `rbenv`/`rvm`" because doing the latter always makes me sad...

**Comment by ghickman** [comment]
@doismellburning – is Docker something we want to consider here too? I've not set up Vagrant in a _long_ time but my recent experience with Docker was unterrible.

**Comment by snim2** [comment]
I've been using Docker for a little while. Dockerfiles are not terrible, probably not dissimilar to Vagrant scripts, I guess?

**Comment by ntoll** [comment]
On 16/04/15 15:10, Kristian Glass wrote:

> #21 https://github.com/PyconUK/pyconuk.github.io/pull/21 - "someone
> who can build the site" - that should be "anyone who can run |vagrant
> up|" rather than "anyone who can set up |rbenv|/|rvm|" because doing the
> latter always makes me sad...
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/PyconUK/pyconuk.github.io/issues/22.

This all sounds really funky. As someone who is inherently lazy about
this sort of stuff can someone (Kristian / George / Sarah???) write up /
provide the appropriate information on what to do as baby steps on the
wiki (then share the link) or (better still) make it part of the README
under the heading "Developer Setup". ;-)

This is important for people who will join the team in the future - all
the required information is in one place.

Best wishes,

N.

**Comment by ntoll** [comment]
Please see: https://github.com/PyconUK/pyconuk.github.io/issues/23 ;-)

**Comment by snim2** [comment]
I'll have a go at a Docker config and will shout here if I get stuck with this weird Ruby stuff :)

**Comment by ghickman** [comment]
@snim2 – brilliant. I'm happy to help out with testing it, etc. I've not actually written a Dockerfile mind…

**Comment by snim2** [comment]
@ghickman Hi there! I've pushed something to the Dockerfile branch. To build do this:

```
$ docker build .
```

and watch for the hash of the resulting container. To run do something like this:

```
$ sudo docker run -ti HASH -p 4000:4000
```

For me, this results in something like the following:

```
$ sudo docker run -ti HASH -p 4000:4000
Configuration file: /pyconuk.github.io-master/_config.yml
            Source: /pyconuk.github.io-master
       Destination: /pyconuk.github.io-master/_site
      Generating... 
                    done.
 Auto-regeneration: enabled for '/pyconuk.github.io-master'
Configuration file: /pyconuk.github.io-master/_config.yml
    Server address: http://127.0.0.1:4000/
  Server running... press ctrl-c to stop.
```

which looks close to correct. However, I cannot actually see the served site in any browser, despite exposing and routing port `4000`.

Any ideas? TIA

**Comment by doismellburning** [comment]
@snim2 You're only binding to localhost. Lets discuss this in the PR?

**Comment by snim2** [comment]
@doismellburning this is on a branch, I didn't create a PR since the code isn't working :)

**Comment by doismellburning** [comment]
@snim2 I'd strongly recommend against "does it work" being a prerequisite for PR creation; e.g. it'd provide a better place for this discussion

**Comment by ghickman** [comment]
@snim2 – another vote for a PR here, I think commenting on lines would be really useful while we figure this out =)

**Comment by snim2** [comment]
OK, have created a PR...

**Comment by ghickman** [comment]
Thanks all for helping get this out!
