### ISSUE TITLE
Add a "developer setup" section to the README

### ISSUE THREAD

**Issue by ntoll** [PyconUK/pyconuk.github.io#23]
As a developer I would like easy to follow baby steps and appropriately referenced resources for setting up a development environment using vagrant/docker/whatever is tech-du-jour for this sort of thing... ;-)

Please don't assume I know what I'm doing. :-D

**Comment by doismellburning** [comment]
Ok, can you help me by explaining exactly what you find unclear with [the current instructions](https://github.com/PyconUK/pyconuk.github.io#usage) please? Obviously it's brief, but actually knowing _what_ you don't find easy to follow / appropriately referenced would be good.

**Comment by doismellburning** [comment]
(I get that as per #22 the steps could be reduced in number and complexity, but given this was filed subsequently, I guess you're talking about the current set?)

**Comment by ntoll** [comment]
OK... I understand the instructions for generating the site. I'm asking for how to set up a recommended development environment. Specifically, I'm fishing for a clear recommendation of a development sandbox technology along with baby-steps instructions for how to set this up (or pointers to the sandbox tech's documentation explaining this). Does this make sense..?

**Comment by ntoll** [comment]
Yes, current set of instructions.

**Comment by ntoll** [comment]
Basically, I'm keen that there are _no_ assumptions in setting up a development environment for the website - including whatever dev sandboxing may be required. We're basically saving ourselves time answering questions like "how do I configure this thing?" in the future.

**Comment by ntoll** [comment]
This appears to be fixed by the merge of #25 and #26
