### ISSUE TITLE
There should be an easy way to run the build checks locally

### ISSUE THREAD

**Issue by inglesp** [PyconUK/pyconuk.github.io#34]
When checking a pull request, Travis runs `bundle exec htmlproof --href-swap ".*pyconuk.org/:/" _site/`.

It should be possible to run this locally, easily, both if you're running inside docker or if you're not.

Assigning to @ghickman cos he seems to enjoy this kind of thing, but don't feel you've got to take it on!

**Comment by ghickman** [comment]
Happy to take a stab at it.

**Comment by inglesp** [comment]
@ghickman, is this fixed by #38?

**Comment by inglesp** [comment]
Covered by https://github.com/PyconUK/pyconuk.org.
