### ISSUE TITLE
CSS on Tables would be nice

### ISSUE THREAD

**Issue by zeth** [PyconUK/pyconuk.github.io#44]
The table on the Schedule page will just do for now. If someone is inclined to find out how to add secondary CSS sheets to a page then some well thought out table padding would be nice, perhaps some zebra striping.

Maybe https://github.com/hawkz would be a more obvious person to do this than me.

The Python.org website CSS has this, which might be helpful:

table.docutils {
    border: 1px solid #ddd;
    min-width: 20%;
    border-radius: 3px;
    margin-top: 10px;
    margin-bottom: 10px;
}

table.docutils td, table.docutils th {
    border: 1px solid #ddd !important;
    border-radius: 3px;
}

table p, table li {
    text-align: left !important;
}

table.docutils th {
    background-color: #eee;
    padding: 0.3em 0.5em;
}

table.docutils td {
    background-color: white;
    padding: 0.3em 0.5em;
}

**Comment by ntoll** [comment]
CSS is explained in the README for this repos. Would love to know what's been missed. Happy to help in any way that I can.
