### ISSUE TITLE
Automated Restructured Text Converter

### ISSUE THREAD

**Issue by zeth** [PyconUK/pyconuk.github.io#45]
There is a Restructured Text Converter listed here:
http://jekyllrb.com/docs/plugins/#converters

On a rainy day I will test it out. If anyone knows Jekyll better and wants to beat me to it, please go ahead.

**Comment by ghickman** [comment]
Raising the @doismellburning bat/jekyll signal here.

**Comment by zeth** [comment]
Thanks very much.

**Comment by zeth** [comment]
I will give a beer for first person who gets it to work :)

**Comment by inglesp** [comment]
Closing, since this is covered by https://github.com/PyconUK/pyconuk.org.

:beer: please!
