### ISSUE TITLE
Table headers

### ISSUE THREAD

**Issue by zeth** [PyconUK/pyconuk.github.io#46]
When you make table headers, e.g.:

``` html
<thead valign="bottom">
  <tr><th class="head">Time</th>
    <th class="head">Room 1</th>
    <th class="head">Room 2</th>
    <th class="head">Room 3</th>
    <th class="head">The Software Sustainability Institute Room</th>
    <th class="head">Bank of America Simulation Centre</th>
  </tr>
</thead>
```

It looks beautiful when you remove the main site's style.css etc, but with it, it looks like this:

![2015-04-25--1429922124_846x727_scrot](https://cloud.githubusercontent.com/assets/945574/7330734/26dae268-eaec-11e4-836e-af61febecf65.png)

Is something in the site CSS too hungry i.e. it is not limited enough to a particular class or id?

**Comment by zeth** [comment]
Not currently I removed headers and just have tables with no header tags. But would be nice to be able to use them.

**Comment by zeth** [comment]
Note to self, this is the commit where I sadly ditched the table headers:
https://github.com/zeth/pyconuk.github.io/commit/163b17005a5a4f87a55f8e6300289f13622f243f

**Comment by inglesp** [comment]
Is this something that @hawkz can help with?
