### ISSUE TITLE
Scrolling down "venue" starts to zoom map

### ISSUE THREAD

**Issue by tjguk** [PyconUK/pyconuk.github.io#7]
If you use the mouse wheel to scroll down the "Venue" page, as you hit the embedded map, its scroll-wheel functionality takes over and it starts to zoom.

Easy enough to stop, move the mouse, and carry on, but if anyone's got any good ideas it might be worth avoiding.

**Comment by ghickman** [comment]
Constraining the map to the same width as the text might be the best option here. I wasn't sure what you meant until I realised the map wasn't the bottom of the page. It seems odd (to my eye) to have a full width element in between two constrained width elements.
